### PR TITLE
Dell BIOSConnect DSA-2021-016

### PR DESCRIPTION
**Pull request by sethbrasile**

### CODE REVIEW

**Review by wmmatt — COMMENTED** [review]
Looks great, nice use of the hash table! Do you have a Dell machine you've tested on I can see the output from?

**Comment by sethbrasile** [comment]
`outputLog=!Failed: This machine is an affected model and does not meet the minimum BIOS version requirement. This machine is vulnerable and needs to be updated. BIOS Version: 1.2.16. BIOS version needed: 1.6.0 or higher`

**Comment by sethbrasile** [comment]
I'll DM you a machine name

**Comment by wmmatt** [comment]
> I'll DM you a machine name

Got it. Looks good 👍

**Review by wmmatt — APPROVED** [review]
Reviewed out put and script, verified all looks good to go!

**Pull request merged**
